services:
  backend:
    build:
      context: .
      dockerfile: backend/project/Dockerfile
    container_name: django_backend
    env_file:
      - ./backend/project/.env
    volumes:
      - ./backend/project:/app
      - static_volume:/app/static

        
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/project/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
  static_volume:  # Добавляем volume для статики
