# Generated by Django 5.1.7 on 2025-03-26 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик')], max_length=255, verbose_name='type')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='phone')),
                ('contact_email', models.CharField(max_length=255, verbose_name='email')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('manager', models.CharField(max_length=255, verbose_name='manager')),
                ('note', models.TextField(verbose_name='note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Counterparty',
                'verbose_name_plural': 'Counterparties',
                'db_table': 'counterparties',
            },
        ),
    ]
